### ISSUE TITLE
Make this installable with pip

### ISSUE THREAD

**Issue by eric-wieser** [mitchgu/TAMProxy-pyHost#1]
Up to you if you use the package index, but it would be good if I could run:

```
pip install git+git://github.com/mitchgu/TAMProxy-pyHost.git
```

And it would install all the dependencies for me.

**Comment by mitchgu** [comment]
Yeah, I had been thinking about it, but I'm not sure if it's in the state yet where it's ready to be a package. For example, right now it reads all its settings from config.yaml, and if it's pip installable, it'd be hard to tweak the settings because it'd install to the python site-packages directory. I think ideally I could change it so users can pass it their own yaml file for easy config, sort of like the logger library. However, I probably won't worry about it now since adding more devices is the priority.

If you know of a better approach, let me know. Never released a python package before.

**Comment by eric-wieser** [comment]
I think you can get the best of both worlds with `pip install -e <download dir>`, which then doesn't move it to site-packages.

**Comment by mitchgu** [comment]
Ok, sounds reasonable to me, I'll merge the pull request.
